start:
  - parallel_async:
      - guardrails
      - inference_pipeline
  - post_treatment

guardrails:
  - RAGGuardrails.guardrails_query_analysis_async

inference_pipeline:
  - pre_treatment
  - data_retrieval
  - augmented_generation

pre_treatment:  
  - parallel_async:
    - RAGPreTreatment.query_standalone_from_history_async
    - RAGPreTreatment.query_translation_async
    - RAGPreTreatment.bypassed_query_rewritting_async
  - RAGPreTreatment.analyse_query_for_metadata_async
  - RAGPreTreatment.metadata_filters_validation_and_correction_async

data_retrieval:
# - parallel_async:
#     - RagRetrieval.semantic_vector_retrieval
#     - RagRetrieval.bm25_retrieval
# - RagRetrieval.hybrid_chunks_selection
- RagRetrieval.hybrid_retrieval_langchain_async
# - RagRetrieval.contextual_compression_selection_async
# - RagRetrieval.reranker_on_retrieved_docs_async

augmented_generation:
  - RAGAugmentedGeneration.rag_augmented_answer_generation_no_streaming_async

post_treatment:
  - RAGPostTreatment.response_post_treatment
  # - RAGPostTreatment.response_post_treatment_async
  # - RAGPostTreatment.response_formating_async
  # - RAGPostTreatment.response_add_quotes_async
  # - RAGPostTreatment.response_verification_async
